# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58004bfad11f7284056f84bd7b485055b56b8723d2048c0061ed99572e64079d6447d5da8a6d3c6f69a4f3ee5d7585b4b6ad275a8e1f13fbd479c3262a7f19a6

test:
  secret_key_base: d8b175fb7fbefda93d7e38282fa7769dbbfecdd36a85a8b55a825ce3d84c301a6099de5cb7c459de20317d4b1490ff1dc150c07008f7c0d05516ee156ba25aa0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
